import type { Metadata } from 'next'

import { dir } from 'i18next'
import { Prompt } from 'next/font/google'

import './globals.css'

import Providers from './providers'
import Navbar from '@/components/Layout/Navbar'
import { cn } from '@/lib/utils'
import { I18nProvider } from '@/localization/i18n'
import { detectLanguage } from '@/localization/server'

export const runtime = 'edge'

const prompt = Prompt({
  weight: ['200', '400', '500'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const lng = await detectLanguage()
  return (
    <I18nProvider language={lng}>
      <html lang={lng} dir={dir(lng)}>
        <body className={cn('min-h-screen bg-background', prompt.className)}>
          <Providers>
            <Navbar />
            <main>{children}</main>
          </Providers>
        </body>
      </html>
    </I18nProvider>
  )
}
